"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

add_newline = false

format = """
[λ ](pink)\
$directory\
$os\
$username\
$git_branch\
$git_status\

$python\
$nodejs\
$rust\
$bun\
$c\
$cpp\
$lua\
$golang\
$php\
$java\
$kotlin\
$haskell\

$time\

$line_break\
$character
"""

[os]
disabled = false
format = "[$symbol](blue) "

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:teal"
style_root = "fg:teal"
format = '[$user ]($style)'

[directory]
format            = "[$path](sky) "
truncation_length = 3
truncate_to_repo  = true
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
format = "[$symbol $branch](bold mauve) "

[git_status]
format     = "($ahead_behind$staged$modified$untracked$deleted$conflicted)"
ahead      = "[⇡$count ](bold sky)"
behind     = "[⇣$count ](bold sky)"
diverged   = "[⇡$ahead_count⇣$behind_count ](bold sky)"
staged     = "[+$count ](bold green)"
modified   = "[●$count ](bold yellow)"
untracked  = "[?$count ](bold text)"
deleted    = "[✘$count ](bold red)"
conflicted = "[⚡$count ](bold red)"

[nodejs]
symbol = ""
format = "[ $symbol $version ](green) "

[rust]
symbol = ""
format = "[ $symbol $version ](red) "

[bun]
symbol = ""
format = "[ $symbol $version ](#F9A8D4) "

[c]
symbol = ""
format = "[ $symbol $version ](#6A8ECC) "

[cpp]
symbol = ""
format = "[ $symbol $version ](bg:#00599C fg:text) "

[lua]
symbol = ""
format = "[ $symbol $version ](bg:lavender fg:#000080) "

[golang]
symbol = ""
format = "[ $symbol $version ](#00ADD8) "

[php]
symbol = ""
format = "[ $symbol $version ](#777BB4) "

[java]
symbol = ""
format = "[ $symbol $version ](#ED8B00) "

[kotlin]
symbol = ""
format = "[ $symbol $version ](#7F52FF) "

[haskell]
symbol = ""
format = "[ $symbol $version ](bg:#5E5086 fg:text) "

[python]
symbol = ""
format = "[ $symbol $version ](#FFD43B) "

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[ $time ](fg:lavender)]($style)'

[line_break]
disabled = false 

[character]
success_symbol = "[❯](green)"
error_symbol   = "[❯](red)"
vimcmd_symbol  = "[❮](blue)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
