#!/usr/bin/env bash

# fzf picker over live sessions, most-recently-attached first.
# Shows truncated path + session name; current session hidden.
current=$(tmux display-message -p '#S')
raw=$(
  tmux list-sessions -F $'#{session_last_attached}\t#{pane_current_path}\t#{session_name}' \
    | sort -t$'\t' -k1,1rn \
    | cut -f2,3 \
    | awk -F'\t' -v cur="$current" '$2 != cur'
)
no_sessions=false
if [[ -z "$raw" ]]; then
  lines=$'(no other sessions)\t__noop__'
  no_sessions=true
else
  lines=$(
    while IFS=$'\t' read -r dir name; do
      short=$(echo "$dir" | awk -F/ 'NF>3{printf ".../%s/%s/%s",$(NF-2),$(NF-1),$NF} NF<=3{print}')
      printf '%s  (%s)\t%s\n' "$short" "$name" "$name"
    done <<< "$raw"
  )
fi
selected=$(FZF_DEFAULT_OPTS= fzf --delimiter=$'\t' --with-nth=1 --prompt='session> ' <<< "$lines") || exit 0
$no_sessions && exit 0
tmux switch-client -t "${selected#*$'\t'}"
